# Generated by Django 5.1.1 on 2024-09-11 03:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user_type',
            name='user',
            field=models.CharField(choices=[('STUDENT', 'student'), ('teacher', 'TEACHER')], max_length=250),
        ),
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('department', models.CharField(choices=[('Software Engineering', 'software engineering'), ('Computer Science', 'computer science'), ('artificial intelligence', 'Artificial Intelligence'), ('Cyber Security', 'cyber security'), ('Information Technology', 'information technology')], max_length=250)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.user_type')),
            ],
        ),
        migrations.CreateModel(
            name='Semester',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('semester', models.CharField(choices=[('Sem1', 'sem1'), ('sem2', 'Sem2'), ('sem3', 'Sem3'), ('Sem4', 'sem4'), ('sem5', 'Sem5'), ('sem6', 'Sem6'), ('sem7', 'Sem7'), ('sem8', 'Sem8')], max_length=250)),
                ('departent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.department')),
            ],
        ),
        migrations.CreateModel(
            name='Section',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('section', models.CharField(choices=[('1M', '1m'), ('2M', '2m'), ('3m', '3M'), ('4m', '4M'), ('5M', '5m'), ('6m', '6M'), ('7M', '7m'), ('8m', '8M')], max_length=250)),
                ('semester', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.semester')),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student_id', models.CharField(max_length=250)),
                ('section', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.section')),
            ],
        ),
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('teacher_id', models.CharField(max_length=250)),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.department')),
            ],
        ),
    ]
