# Generated by Django 5.1.1 on 2024-09-11 06:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_user_type_user_department_semester_section_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='department',
            name='user',
        ),
        migrations.RenameField(
            model_name='semester',
            old_name='departent',
            new_name='department',
        ),
        migrations.AlterField(
            model_name='department',
            name='department',
            field=models.CharField(choices=[('software engineering', 'Software Engineering'), ('computer science', 'Computer Science'), ('artificial intelligence', 'Artificial Intelligence'), ('Cyber Security', 'cyber security'), ('information technology', 'Information Technology')], max_length=250),
        ),
        migrations.AlterField(
            model_name='section',
            name='section',
            field=models.CharField(choices=[('1m', '1M'), ('2m', '2M'), ('3M', '3m'), ('4M', '4m'), ('5m', '5M'), ('6m', '6M'), ('7M', '7m'), ('8m', '8M')], max_length=250),
        ),
        migrations.AlterField(
            model_name='semester',
            name='semester',
            field=models.CharField(choices=[('Sem1', 'sem1'), ('sem2', 'Sem2'), ('sem3', 'Sem3'), ('Sem4', 'sem4'), ('Sem5', 'sem5'), ('sem6', 'Sem6'), ('sem7', 'Sem7'), ('sem8', 'Sem8')], max_length=250),
        ),
        migrations.DeleteModel(
            name='user_type',
        ),
    ]
