# Generated by Django 5.1.1 on 2024-09-12 06:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_remove_department_user_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='address',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='student',
            name='cnic_no',
            field=models.CharField(blank=True, max_length=13, null=True),
        ),
        migrations.AddField(
            model_name='student',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
        migrations.AddField(
            model_name='student',
            name='last_login',
            field=models.DateTimeField(blank=True, null=True, verbose_name='last login'),
        ),
        migrations.AddField(
            model_name='student',
            name='password',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='student',
            name='stu_father_name',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='student',
            name='stu_name',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='department',
            name='department',
            field=models.CharField(choices=[('Software Engineering', 'software engineering'), ('Computer Science', 'computer science'), ('Artificial Intelligence', 'artificial intelligence'), ('Cyber Security', 'cyber security'), ('information technology', 'Information Technology')], max_length=250),
        ),
        migrations.AlterField(
            model_name='section',
            name='section',
            field=models.CharField(choices=[('1M', '1m'), ('2M', '2m'), ('3M', '3m'), ('4m', '4M'), ('1E', '1e'), ('2E', '2e'), ('3E', '3e'), ('4e', '4E')], max_length=250),
        ),
        migrations.AlterField(
            model_name='semester',
            name='semester',
            field=models.CharField(choices=[('sem1', 'Sem1'), ('Sem2', 'sem2'), ('Sem3', 'sem3'), ('Sem4', 'sem4'), ('sem5', 'Sem5'), ('Sem6', 'sem6'), ('sem7', 'Sem7'), ('sem8', 'Sem8')], max_length=250),
        ),
        migrations.AlterField(
            model_name='student',
            name='student_id',
            field=models.CharField(max_length=250, unique=True),
        ),
    ]
