# Generated by Django 5.1.1 on 2024-09-15 05:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_student_address_student_cnic_no_student_image_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='image',
        ),
        migrations.RemoveField(
            model_name='student',
            name='last_login',
        ),
        migrations.RemoveField(
            model_name='student',
            name='password',
        ),
        migrations.AlterField(
            model_name='department',
            name='department',
            field=models.CharField(max_length=250),
        ),
        migrations.AlterField(
            model_name='section',
            name='section',
            field=models.CharField(max_length=250),
        ),
        migrations.AlterField(
            model_name='semester',
            name='semester',
            field=models.CharField(max_length=250),
        ),
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=100, null=True)),
                ('section', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.section')),
            ],
        ),
        migrations.CreateModel(
            name='Professor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('teacher_id', models.CharField(blank=True, max_length=250, null=True)),
                ('name', models.CharField(blank=True, max_length=250, null=True)),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.department')),
                ('section', models.ManyToManyField(to='users.section')),
                ('subject', models.ManyToManyField(to='users.subject')),
            ],
        ),
        migrations.DeleteModel(
            name='Teacher',
        ),
    ]
